spring:
  application:
    name: common
  profiles:
    active: dev
# 日志配置
logging:
  level:
    com.achobeta: debug
    org.springframework: warn
    tech.powerjob.worker.background: warn
  config: classpath:logback-plus.xml
