okr:
  db:
    host: 127.0.0.1
    port: 3306
    database: db_okr_system
    username: root
    password: mmsszsd666
server:
  port: 5678
--- # 数据源配置
spring:
  datasource:
    url: jdbc:mysql://${okr.db.host}:${okr.db.port}/${okr.db.database}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: ${okr.db.username}
    password: ${okr.db.password}
    driver-class-name: com.mysql.jdbc.Driver

spring.data:
  # redis
  redis:
    # 地址
    host: 127.0.0.1
    # 端口
    port: 6379