spring:
  application:
    name: center-service
    version: 1.0
  profiles:
    active: @profiles.active@
  jackson: # Spring 返回默认用 jackson 序列化的
    date-format: yyyy-MM-dd HH:mm:ss # ⽇期格式
    default-property-inclusion: NON_NULL # 不为null序列化
    time-zone: Asia/Shanghai
#  servlet:
#    multipart: # 上传文件不限大小
#      max-file-size: -1
#      max-request-size: -1
#      file-size-threshold: 80

# 日志配置
logging:
  level:
    com.macaku: @logging.level@
    org.springframework: warn
    tech.powerjob.worker.background: warn
  config: classpath:logback-plus.xml


# mp设置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml # Mapper.xml文件地址,默认值
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler #设置枚举处理器
    map-underscore-to-camel-case: true # 是否开启下划线和驼峰的映射
    cache-enabled: false # 是否开启二级缓存
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1 #逻辑已删除值(默认为1)
      logic-not-delete-value: 0 #逻辑未删除值(默认为0)
      # todo: 考虑用什么 id
      id-type: auto #id为雪花算法生成 设置为none->为遵循版本默认，可见这个版本默认为assign_id
      update-strategy: not_null #更新策略:只更新非空字段