okr:
  db:
    host: 127.0.0.1
    port: 3306
    database: db_okr_system
    username: root
    password: mmsszsd666
server:
  port: 1701
--- # 数据源配置
spring:
  datasource:
    url: jdbc:mysql://${okr.db.host}:${okr.db.port}/${okr.db.database}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: ${okr.db.username}
    password: ${okr.db.password}
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    # 地址
    host: 39.108.10.200
    # 端口
    port: 6379
    # 数据库索引
    database: 0
    # 密码(如没有密码请注释掉)
    password: Lmz171309
    # 连接超时时间
    connect-timeout: 10s
    # 是否开启ssl
    ssl.enabled: false

media:
  root: D:/
  map: media/

wx:
  appid: wx9efa37f247f01d10
  secret: ef6c3f39e28f30d8916819541cb8bc00
  invite:
    sceneKey: teamId
    secret: secret
    page:
    checkPath: false
    envVersion: develop
    width: 430
    auto_color: false
    lineColor:
      r: 20
      g: 133
      b: 238
    isHyaline: false

limit:
  time:
    second: 86400
    multiple: 2

