okr:
  db:
    host: 127.0.0.1
    port: 3306
    database: db_okr_system
    username: root
    password: mmsszsd666
server:
  port: 1701
--- # 数据源配置
spring:
  datasource:
    url: jdbc:mysql://${okr.db.host}:${okr.db.port}/${okr.db.database}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8&allowPublicKeyRetrieval=true
    username: ${okr.db.username}
    password: ${okr.db.password}
    driver-class-name: com.mysql.jdbc.Driver

spring.data:
  # redis
  redis:
    # 地址
    host: 127.0.0.1
    # 端口
    port: 6379

media:
  root: D:/
  map: media/

wx:
  appid: wx9efa37f247f01d10
  secret: ef6c3f39e28f30d8916819541cb8bc00
  invite:
    sceneKey: teamId
    page:
    checkPath: false
    envVersion: develop
    width: 430
    auto_color: false
    lineColor:
      r: 70
      g: 53
      b: 100
    isHyaline: false

limit:
  time:
    second: 86400
    multiple: 2

